config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users
  resources :relacionamentos

## devise controllers for users
  devise_for :user, controllers: {
      # confirmations: 'users/confirmations',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      # unlocks: 'users/unlocks',
  }, skip: [:sessions]

  as :user do
    get 'login' => 'users/sessions#new', as: :new_user_session
    post 'login' => 'users/sessions#create', as: :user_session
    delete 'logout' => 'users/sessions#destroy', as: :destroy_user_session
    get 'register' => 'users/registrations#new'
  end

  get 'user/:user_id', to: 'users#visualizar'

  root to: "application#home"



end

app/views/aux/_topbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand"><%= image_tag 'logo_mini.png' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_url %>"> Home <span class="sr-only">(current)</span></a></li>
        <li class="active"><a href="<%= users_path %>"> Usuarios <span class="sr-only">(current)</span></a></li>
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                 aria-expanded="false">Posts <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a><%= link_to 'Novo', new_post_path %></a></li>
                <li><a><%= link_to 'Listar', posts_path %></a></li>
              </ul>
            </li>
            </ul>
            <form class="navbar-form navbar-left">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Palavra-chave ou Usuario">
              </div>
              <button type="submit" class="btn btn-default">Buscar</button>
            </form>
        <% end %>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                   aria-expanded="false"><%= current_user.login %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a><%= link_to 'Perfil', edit_user_registration_path, :method => 'get' %> </a></li>
                  <li role="separator" class="divider"></li>
                  <li><a><%= link_to 'Sair', destroy_user_session_path, :method => 'delete' %> </a></li>
                </ul>
              </li>
          <% else %>
              <li class="nav-item"> <%= link_to 'Entrar', user_session_path %> </li>
              <li class="nav-item"> <%= link_to 'Registrar-se', register_path %> </li>
          <% end %>
        </ul>
        </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>